name: TheSkeletonBosses
version: 1.1.0
main: gersom.TSB
api-version: 1.17
author: Gersom

commands:
  tsb:
    description: TSB command
    aliases: [tsb]
    usage: /<command> [subcommand]
    permission-message: ยง4You don't have permission to use this command
    subcommands:
      help:
        description: Shows help message
        usage: /<command> help
      list:
        description: Shows list of commands
        usage: /<command> list
      reload:
        description: Reloads config.yml
        usage: /<command> reload
      author:
        description: Shows author of plugin
        usage: /<command> author
      version:
        description: Shows version of plugin
        usage: /<command> version
      spawn:
        description: Spawns a custom mob
        usage: /<command> spawn [emperor, king]

permissions:
  the-skeleton-bosses.use:
    description: Allows player to use TSB commands
    default: op